spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/redis_demo?useSSL=false&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 50
      # 获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.redis.dao